import type { ChatThread, MatchLookingFor, MatchProfile } from "./types";

/** Indian / South Asian women portraits (Unsplash) */
const P = [
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1619895862022-09114b41f16f?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1621786030484-4c855eed6974?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1614283233556-f35b0c801ef1?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1602233158242-3ba0ac4d6303?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1557053910-d9eadeed1c58?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1588516903720-8ceb67f35541?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80",
];

function prefs(partial: Partial<MatchLookingFor> = {}): MatchLookingFor {
  return {
    ageMin: 21,
    ageMax: 50,
    location: "All Ok",
    height: "All Ok",
    diet: "All Ok",
    maritalStatus: "Unmarried",
    motherTongue: "Hindi",
    mangalDosh: "All Ok",
    occupation: "All Ok",
    monthlySalary: "All Ok",
    education: "All Ok",
    ...partial,
  };
}

function m(
  partial: Omit<
    MatchProfile,
    | "preferences"
    | "lifestyle"
    | "kundli"
    | "lookingFor"
    | "about"
    | "family"
    | "religion"
    | "activeRank"
    | "isNew"
    | "companyName"
  > &
    Partial<MatchProfile>
): MatchProfile {
  const { preferences: customPrefs, ...rest } = partial;
  return {
    religion: "Hindu",
    activeRank: 2,
    isNew: false,
    companyName: "",
    lookingFor: "A kind, family-oriented partner.",
    about: "Family-oriented and grounded. Looking for a respectful marriage.",
    family: "Parents live nearby. Close-knit family.",
    lifestyle: ["Vegetarian", "Does not drink", "Does not smoke"],
    kundli: "Mangal Dosh details shared after interest.",
    preferences: customPrefs || prefs({ location: `All ${partial.state}` }),
    ...rest,
  };
}

export const MATCHES: MatchProfile[] = [
  m({
    id: "m1",
    name: "Ananya Sharma",
    age: 27,
    city: "Jaipur",
    state: "Rajasthan",
    occupation: "Private Company",
    education: "Bachelor degree",
    community: "Brahmin",
    motherTongue: "Hindi",
    height: "5'5\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Jaipur, Rajasthan",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    activeRank: 1,
    isNew: true,
    photos: [P[0]],
    phone: "9876543210",
    about: "Grew up in Jaipur. Values family, festivals, and a simple respectful marriage.",
    preferences: prefs({ ageMin: 26, ageMax: 35, location: "All Rajasthan", occupation: "Private Company, Government Job" }),
  }),
  m({
    id: "m2",
    name: "Meera Iyer",
    age: 26,
    city: "Bengaluru",
    state: "Karnataka",
    occupation: "Private Company",
    education: "Master degree",
    community: "Iyer (Brahmin)",
    motherTongue: "Tamil",
    height: "5'4\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Don't know",
    salary: "₹1 Lakh – ₹2 Lakh",
    companyLocation: "Bengaluru, Karnataka",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active 2h ago",
    activeRank: 1,
    isNew: true,
    photos: [P[1]],
    phone: "9876501234",
    preferences: prefs({ location: "All Karnataka, All Tamil Nadu", motherTongue: "Tamil, Hindi" }),
  }),
  m({
    id: "m3",
    name: "Kavya Reddy",
    age: 28,
    city: "Hyderabad",
    state: "Telangana",
    occupation: "Private Company",
    education: "Professional degree",
    community: "Reddy",
    motherTongue: "Telugu",
    height: "5'6\"",
    diet: "Eggetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Anshik",
    salary: "₹1 Lakh – ₹2 Lakh",
    companyLocation: "Hyderabad, Telangana",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    photos: [P[2]],
    phone: "9123456780",
    preferences: prefs({ location: "All Telangana", diet: "Eggetarian, Vegetarian", mangalDosh: "All Ok" }),
  }),
  m({
    id: "m4",
    name: "Riya Patel",
    age: 25,
    city: "Ahmedabad",
    state: "Gujarat",
    occupation: "Business",
    education: "Graduate",
    community: "Patel",
    motherTongue: "Gujarati",
    height: "5'3\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹30,000 – ₹50,000",
    companyLocation: "Ahmedabad, Gujarat",
    companyName: "Family business",
    profileFor: "Myself",
    verified: false,
    activeLabel: "Active this week",
    photos: [P[3]],
    phone: "9988776655",
    preferences: prefs({ location: "All Gujarat", occupation: "Business, Private Company" }),
  }),
  m({
    id: "m5",
    name: "Sneha Deshmukh",
    age: 29,
    city: "Pune",
    state: "Maharashtra",
    occupation: "Government Job",
    education: "Master degree",
    community: "Maratha",
    motherTongue: "Marathi",
    height: "5'5\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Pune, Maharashtra",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    activeRank: 1,
    photos: [P[4]],
    phone: "9811122233",
    preferences: prefs({ location: "All Maharashtra", occupation: "Government Job, Defence Job" }),
  }),
  m({
    id: "m6",
    name: "Aditi Nair",
    age: 27,
    city: "Kochi",
    state: "Kerala",
    occupation: "Private Company",
    education: "Graduate",
    community: "Nair",
    motherTongue: "Malayalam",
    height: "5'4\"",
    diet: "Non-Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Don't know",
    salary: "₹30,000 – ₹50,000",
    companyLocation: "Kochi, Kerala",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active recently",
    photos: [P[5]],
    phone: "9900112233",
    preferences: prefs({ location: "All Kerala", diet: "All Ok", motherTongue: "Malayalam" }),
  }),
  m({
    id: "m7",
    name: "Ishita Banerjee",
    age: 26,
    city: "Kolkata",
    state: "West Bengal",
    occupation: "Private Company",
    education: "Professional degree",
    community: "Kayastha",
    motherTongue: "Bengali",
    height: "5'4\"",
    diet: "Non-Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Kolkata, West Bengal",
    profileFor: "Myself",
    verified: false,
    activeLabel: "Active this week",
    photos: [P[6]],
    phone: "9765432109",
    preferences: prefs({ location: "All West Bengal", motherTongue: "Bengali, Hindi" }),
  }),
  m({
    id: "m8",
    name: "Priya Gupta",
    age: 24,
    city: "Lucknow",
    state: "Uttar Pradesh",
    occupation: "Government Job",
    education: "Master degree",
    community: "Gupta",
    motherTongue: "Hindi",
    height: "5'3\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Lucknow, Uttar Pradesh",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    activeRank: 1,
    isNew: true,
    photos: [P[7]],
    phone: "9898989898",
    preferences: prefs({ location: "All Uttar Pradesh", occupation: "Government Job" }),
  }),
  m({
    id: "m9",
    name: "Asha Kumari",
    age: 30,
    city: "North Delhi",
    state: "Delhi",
    occupation: "Private Company",
    education: "Bachelor degree",
    community: "Brahmin - Bhumihar",
    motherTongue: "Hindi",
    height: "5'2\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹15,000 – ₹30,000",
    companyLocation: "Patna, Bihar",
    profileFor: "Sister",
    verified: true,
    activeLabel: "Active this week",
    photos: [P[8]],
    phone: "9812345670",
    about: "Looking for a simple, respectful alliance with family involvement from the start.",
    preferences: prefs({
      ageMin: 21,
      ageMax: 50,
      location: "All Bihar",
      height: "All Ok",
      diet: "All Ok",
      maritalStatus: "Unmarried, Divorced / Getting Divorced, Widow",
      motherTongue: "Hindi",
      mangalDosh: "All Ok",
      occupation: "Government / Defense, Business",
      monthlySalary: "All Ok",
      education: "All Ok",
    }),
  }),
  m({
    id: "m10",
    name: "Neha Verma",
    age: 25,
    city: "Rohtak",
    state: "Haryana",
    occupation: "Student",
    education: "Graduate",
    community: "Brahmin",
    motherTongue: "Hindi",
    height: "5'4\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "Don't want to tell",
    companyLocation: "Rohtak, Haryana",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    photos: [P[9]],
    phone: "9823456710",
    preferences: prefs({ location: "All Haryana, All Delhi", occupation: "All Ok" }),
  }),
  m({
    id: "m11",
    name: "Pooja Singh",
    age: 28,
    city: "Chandigarh",
    state: "Punjab",
    occupation: "Government Job",
    education: "Post Graduate",
    community: "Jat",
    motherTongue: "Punjabi",
    height: "5'6\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Anshik",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Chandigarh",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active 2h ago",
    photos: [P[10]],
    phone: "9834567810",
    preferences: prefs({ location: "All Punjab, All Haryana", motherTongue: "Punjabi, Hindi" }),
  }),
  m({
    id: "m12",
    name: "Divya Joshi",
    age: 27,
    city: "Indore",
    state: "Madhya Pradesh",
    occupation: "Private Company",
    education: "Graduate",
    community: "Brahmin",
    motherTongue: "Hindi",
    height: "5'3\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹30,000 – ₹50,000",
    companyLocation: "Indore, Madhya Pradesh",
    profileFor: "Myself",
    verified: false,
    activeLabel: "Active this week",
    photos: [P[11]],
    phone: "9845678910",
    preferences: prefs({ location: "All Madhya Pradesh" }),
  }),
  m({
    id: "m13",
    name: "Shreya Das",
    age: 26,
    city: "Bhubaneswar",
    state: "Odisha",
    occupation: "Government Job",
    education: "Graduate",
    community: "Kayastha",
    motherTongue: "Odia",
    height: "5'2\"",
    diet: "Non-Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Don't know",
    salary: "₹20,000 – ₹30,000",
    companyLocation: "Bhubaneswar, Odisha",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active recently",
    photos: [P[12]],
    phone: "9856789010",
    preferences: prefs({ location: "All Odisha", motherTongue: "Odia, Hindi" }),
  }),
  m({
    id: "m14",
    name: "Anjali Sharma",
    age: 29,
    city: "Patna",
    state: "Bihar",
    occupation: "Business",
    education: "Graduate",
    community: "Brahmin",
    motherTongue: "Hindi",
    height: "5'4\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Patna, Bihar",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    photos: [P[13]],
    phone: "9867890120",
    preferences: prefs({ location: "All Bihar", occupation: "Business, Private Company" }),
  }),
  m({
    id: "m15",
    name: "Lakshmi Rao",
    age: 28,
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    occupation: "Private Company",
    education: "Master degree",
    community: "Kshatriya / Rajput",
    motherTongue: "Telugu",
    height: "5'5\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹1 Lakh – ₹2 Lakh",
    companyLocation: "Visakhapatnam, Andhra Pradesh",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active this week",
    photos: [P[14]],
    phone: "9878901230",
    preferences: prefs({ location: "All Andhra Pradesh, All Telangana", motherTongue: "Telugu" }),
  }),
  m({
    id: "m16",
    name: "Sanjana Kapoor",
    age: 25,
    city: "Mumbai",
    state: "Maharashtra",
    occupation: "Private Company",
    education: "Graduate",
    community: "Khatri",
    motherTongue: "Hindi",
    height: "5'5\"",
    diet: "Eggetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹1 Lakh – ₹2 Lakh",
    companyLocation: "Mumbai, Maharashtra",
    profileFor: "Myself",
    verified: false,
    activeLabel: "Active 2h ago",
    isNew: true,
    photos: [P[15]],
    phone: "9889012340",
    preferences: prefs({ location: "All Maharashtra, All Delhi", diet: "All Ok" }),
  }),
  m({
    id: "m17",
    name: "Tanvi Agarwal",
    age: 27,
    city: "Jaipur",
    state: "Rajasthan",
    occupation: "Business",
    education: "Graduate",
    community: "Agarwal",
    motherTongue: "Rajasthani",
    height: "5'3\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Jaipur, Rajasthan",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    photos: [P[16]],
    phone: "9890123450",
    preferences: prefs({ location: "All Rajasthan", motherTongue: "Rajasthani, Hindi", occupation: "Business" }),
  }),
  m({
    id: "m18",
    name: "Fatima Siddiqui",
    age: 26,
    city: "Hyderabad",
    state: "Telangana",
    occupation: "Private Company",
    education: "Graduate",
    community: "Syed",
    motherTongue: "Urdu",
    height: "5'4\"",
    diet: "Non-Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Don't know",
    salary: "₹30,000 – ₹50,000",
    companyLocation: "Hyderabad, Telangana",
    profileFor: "Myself",
    religion: "Muslim",
    verified: true,
    activeLabel: "Active this week",
    photos: [P[17]],
    phone: "9901234560",
    preferences: prefs({ location: "All Telangana", motherTongue: "Urdu, Hindi", mangalDosh: "All Ok" }),
  }),
  m({
    id: "m19",
    name: "Gurpreet Kaur",
    age: 28,
    city: "Amritsar",
    state: "Punjab",
    occupation: "Defence Job",
    education: "Graduate",
    community: "Sikh",
    motherTongue: "Punjabi",
    height: "5'6\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Amritsar, Punjab",
    profileFor: "Myself",
    religion: "Sikh",
    verified: true,
    activeLabel: "Active today",
    photos: [P[18]],
    phone: "9912345670",
    preferences: prefs({ location: "All Punjab", occupation: "Defence Job, Government Job", motherTongue: "Punjabi" }),
  }),
  m({
    id: "m20",
    name: "Nisha Yadav",
    age: 24,
    city: "Ayodhya",
    state: "Uttar Pradesh",
    occupation: "Student",
    education: "Graduate",
    community: "Yadav",
    motherTongue: "Hindi",
    height: "5'2\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "Don't want to tell",
    companyLocation: "Ayodhya, Uttar Pradesh",
    profileFor: "Myself",
    verified: false,
    activeLabel: "Active recently",
    photos: [P[19]],
    phone: "9923456780",
    preferences: prefs({ location: "All Uttar Pradesh", height: "All Ok", education: "All Ok" }),
  }),
  m({
    id: "m21",
    name: "Keerthana R",
    age: 26,
    city: "Chennai",
    state: "Tamil Nadu",
    occupation: "Private Company",
    education: "Master degree",
    community: "Mudaliar",
    motherTongue: "Tamil",
    height: "5'4\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Chennai, Tamil Nadu",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    activeRank: 1,
    isNew: true,
    photos: [P[0]],
    phone: "9934567890",
    preferences: prefs({ location: "All Tamil Nadu, All Karnataka", motherTongue: "Tamil" }),
  }),
  m({
    id: "m22",
    name: "Ankita Baruah",
    age: 27,
    city: "Guwahati",
    state: "Assam",
    occupation: "Government Job",
    education: "Graduate",
    community: "Kalita",
    motherTongue: "Assamese",
    height: "5'3\"",
    diet: "Non-Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Don't know",
    salary: "₹30,000 – ₹50,000",
    companyLocation: "Guwahati, Assam",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active this week",
    photos: [P[1]],
    phone: "9945678901",
    preferences: prefs({ location: "All Assam", motherTongue: "Assamese, Hindi" }),
  }),
  m({
    id: "m23",
    name: "Pallavi Kumari",
    age: 25,
    city: "Ranchi",
    state: "Jharkhand",
    occupation: "Private Company",
    education: "Graduate",
    community: "Brahmin",
    motherTongue: "Hindi",
    height: "5'4\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹20,000 – ₹30,000",
    companyLocation: "Ranchi, Jharkhand",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    photos: [P[2]],
    phone: "9956789012",
    preferences: prefs({ location: "All Jharkhand, All Bihar" }),
  }),
  m({
    id: "m24",
    name: "Sneha Rawat",
    age: 28,
    city: "Dehradun",
    state: "Uttarakhand",
    occupation: "Government Job",
    education: "Master degree",
    community: "Rajput",
    motherTongue: "Hindi",
    height: "5'5\"",
    diet: "Vegetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "Anshik",
    salary: "₹50,000 – ₹1 Lakh",
    companyLocation: "Dehradun, Uttarakhand",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active 2h ago",
    photos: [P[3]],
    phone: "9967890123",
    preferences: prefs({ location: "All Uttarakhand, All Delhi", occupation: "Government Job" }),
  }),
  m({
    id: "m25",
    name: "Simran Bhatia",
    age: 26,
    city: "Chandigarh",
    state: "Chandigarh",
    occupation: "Private Company",
    education: "Graduate",
    community: "Khatri",
    motherTongue: "Punjabi",
    height: "5'5\"",
    diet: "Eggetarian",
    maritalStatus: "Unmarried",
    mangalDosh: "No",
    salary: "₹1 Lakh – ₹2 Lakh",
    companyLocation: "Chandigarh",
    profileFor: "Myself",
    verified: true,
    activeLabel: "Active today",
    isNew: true,
    photos: [P[4]],
    phone: "9978901234",
    preferences: prefs({ location: "All Chandigarh, All Punjab, All Haryana", motherTongue: "Punjabi, Hindi" }),
  }),
];

export const THREADS: ChatThread[] = [
  {
    id: "c1",
    matchId: "m1",
    lastMessage: "Would you like to know more about my family?",
    time: "05/08/26",
    unread: 1,
    folder: "primary",
    messages: [
      { from: "them", text: "Namaste. Thank you for showing interest.", time: "Yesterday" },
      { from: "me", text: "Namaste Ananya. What are you looking for in a life partner?", time: "Yesterday" },
      { from: "them", text: "Someone kind and clear with family. Would you like to know more about my family?", time: "10:14 am" },
    ],
  },
  {
    id: "c2",
    matchId: "m5",
    lastMessage: "7700140748 WhatsApp number shared",
    time: "05/08/26",
    unread: 0,
    folder: "primary",
    messages: [
      { from: "me", text: "Hello. I saw you are in Pune.", time: "Mon" },
      { from: "them", text: "Yes. You can WhatsApp on 7700140748.", time: "Yesterday" },
    ],
  },
  {
    id: "c3",
    matchId: "m2",
    lastMessage: "Hello Meera",
    time: "04/08/26",
    unread: 0,
    folder: "primary",
    messages: [
      { from: "them", text: "Hello. My parents usually like to be included early.", time: "Mon" },
      { from: "me", text: "Hello Meera", time: "Mon" },
    ],
  },
  {
    id: "c4",
    matchId: "m3",
    lastMessage: "Hi Kavya, my name is Saurabh. I saw your profile on Samaj Saathi.",
    time: "04/08/26",
    unread: 0,
    folder: "sent",
    status: "pending",
    messages: [
      { from: "me", text: "Hi Kavya, my name is Saurabh. I saw your profile on Samaj Saathi.", time: "04/08/26" },
    ],
  },
  {
    id: "c5",
    matchId: "m4",
    lastMessage: "Hi Riya, my name is Saurabh. Would you like to connect?",
    time: "04/08/26",
    unread: 0,
    folder: "sent",
    status: "pending",
    messages: [
      { from: "me", text: "Hi Riya, my name is Saurabh. Would you like to connect?", time: "04/08/26" },
    ],
  },
  {
    id: "c6",
    matchId: "m6",
    lastMessage: "Hello Aditi, Myself Saurabh. Looking forward to hearing from you.",
    time: "03/08/26",
    unread: 0,
    folder: "sent",
    status: "pending",
    messages: [
      { from: "me", text: "Hello Aditi, Myself Saurabh. Looking forward to hearing from you.", time: "03/08/26" },
    ],
  },
  {
    id: "c7",
    matchId: "m8",
    lastMessage: "Hi Priya, my name is Saurabh. I liked your biodata.",
    time: "02/08/26",
    unread: 0,
    folder: "sent",
    status: "rejected",
    messages: [
      { from: "me", text: "Hi Priya, my name is Saurabh. I liked your biodata.", time: "02/08/26" },
    ],
  },
];

export function getMatch(id: string) {
  return MATCHES.find((m) => m.id === id);
}
